### PR TITLE
chore: use univ3 swap path for more efficient crv dump

### PR DESCRIPTION
**Pull request by btcookies**
Tests show using univ3 provides a more efficient CRV -> WBTC swap resulting in more yield for strategy. Addresses https://github.com/Badger-Finance/badger-multisig/issues/474

Screen Shot 2022-09-26 at 2 04 11 PM

### CODE REVIEW

**Comment by GalloDaSballo** [comment]
Having Watchpug review as well

**Review by shuklaayush — COMMENTED** [review]
Looks good. Maybe remove references to the swapr router

**Comment by GalloDaSballo** [comment]
Did you guys run tests? My tests don't even compile

**Comment by GalloDaSballo** [comment]
Was getting `STF` on `are_you_trying` that's because we don't set the allowance on initialize, will push fix

**Comment by GalloDaSballo** [comment]
Merged after review LGTM

**Comment by GalloDaSballo** [comment]
1 test fails `test_upgrade_gauge_factory` as it's obsolete

**Pull request merged**
